name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node.js v19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - run: npm ci
      - run: npm test
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
